# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: api/luster/label.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'api/luster/label.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.api import field_behavior_pb2 as google_dot_api_dot_field__behavior__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x16\x61pi/luster/label.proto\x12\x12\x62lueapi.api.luster\x1a\x1fgoogle/api/field_behavior.proto\"y\n\x05Label\x12\n\n\x02id\x18\x01 \x01(\t\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\r\n\x05\x63olor\x18\x03 \x01(\t\x12\x13\n\x0b\x64\x65scription\x18\x04 \x01(\t\x12\x18\n\ncreated_at\x18\x05 \x01(\tB\x04\xe2\x41\x01\x03\x12\x18\n\nupdated_at\x18\x06 \x01(\tB\x04\xe2\x41\x01\x03\x42\x66\n cloud.alphaus.blueapi.api.lusterB\x13\x41piLusterLabelProtoZ-github.com/alphauslabs/blue-sdk-go/api/lusterb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'api.luster.label_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n cloud.alphaus.blueapi.api.lusterB\023ApiLusterLabelProtoZ-github.com/alphauslabs/blue-sdk-go/api/luster'
  _globals['_LABEL'].fields_by_name['created_at']._loaded_options = None
  _globals['_LABEL'].fields_by_name['created_at']._serialized_options = b'\342A\001\003'
  _globals['_LABEL'].fields_by_name['updated_at']._loaded_options = None
  _globals['_LABEL'].fields_by_name['updated_at']._serialized_options = b'\342A\001\003'
  _globals['_LABEL']._serialized_start=79
  _globals['_LABEL']._serialized_end=200
# @@protoc_insertion_point(module_scope)
