# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: api/ripple/v1/adjustmententry.proto
# Protobuf Python Version: 6.30.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    30,
    0,
    '',
    'api/ripple/v1/adjustmententry.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n#api/ripple/v1/adjustmententry.proto\x12\x15\x62lueapi.api.ripple.v1\"\xea\x01\n\x0f\x41\x64justmentEntry\x12\n\n\x02id\x18\x01 \x01(\t\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\x42\n\x07\x61\x63\x63ount\x18\x03 \x01(\x0b\x32\x31.blueapi.api.ripple.v1.AdjustmentEntryAccountInfo\x12\x39\n\x05\x65ntry\x18\x04 \x01(\x0b\x32*.blueapi.api.ripple.v1.AdjustmentEntryInfo\x12>\n\x07setting\x18\x05 \x01(\x0b\x32-.blueapi.api.ripple.v1.AdjustmentEntrySetting\"\xa5\x01\n\x1a\x41\x64justmentEntryAccountInfo\x12\n\n\x02id\x18\x01 \x01(\t\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\x0e\n\x06vendor\x18\x03 \x01(\t\x12\x19\n\x11\x62illingInternalId\x18\x04 \x01(\t\x12\x16\n\x0e\x62illingGroupId\x18\x05 \x01(\t\x12\x18\n\x10\x62illingGroupName\x18\x06 \x01(\t\x12\x10\n\x08\x63urrency\x18\x07 \x01(\t\"\xd6\x01\n\x13\x41\x64justmentEntryInfo\x12\x17\n\x0f\x63\x61lculationType\x18\x01 \x01(\t\x12\x1b\n\x13\x61\x64justmentEntryType\x18\x02 \x01(\t\x12\x13\n\x0b\x64\x65scription\x18\x03 \x01(\t\x12\x13\n\x0bproductCode\x18\x04 \x01(\t\x12\x13\n\x0bproductName\x18\x05 \x01(\t\x12\x10\n\x08\x63urrency\x18\x06 \x01(\t\x12\x0e\n\x06\x61mount\x18\x07 \x01(\x01\x12\x14\n\x0ctimeInterval\x18\x08 \x01(\t\x12\x12\n\nusageStart\x18\t \x01(\t\"\xab\x01\n\x16\x41\x64justmentEntrySetting\x12\r\n\x05\x61pply\x18\x01 \x01(\x08\x12\x14\n\x0c\x65xchangeRate\x18\x02 \x01(\x01\x12\x0f\n\x07taxFree\x18\x03 \x01(\x08\x12\x14\n\x0c\x61llocateType\x18\x04 \x01(\t\x12\x11\n\tsplitType\x18\x05 \x01(\t\x12\x12\n\noriginalId\x18\x06 \x01(\t\x12\x10\n\x08splitted\x18\x07 \x01(\x08\x12\x0c\n\x04term\x18\x08 \x01(\x05\x42v\n#cloud.alphaus.blueapi.api.ripple.v1B\x1d\x41piRippleAdjustmentEntryProtoZ0github.com/alphauslabs/blue-sdk-go/api/ripple/v1b\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'api.ripple.v1.adjustmententry_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n#cloud.alphaus.blueapi.api.ripple.v1B\035ApiRippleAdjustmentEntryProtoZ0github.com/alphauslabs/blue-sdk-go/api/ripple/v1'
  _globals['_ADJUSTMENTENTRY']._serialized_start=63
  _globals['_ADJUSTMENTENTRY']._serialized_end=297
  _globals['_ADJUSTMENTENTRYACCOUNTINFO']._serialized_start=300
  _globals['_ADJUSTMENTENTRYACCOUNTINFO']._serialized_end=465
  _globals['_ADJUSTMENTENTRYINFO']._serialized_start=468
  _globals['_ADJUSTMENTENTRYINFO']._serialized_end=682
  _globals['_ADJUSTMENTENTRYSETTING']._serialized_start=685
  _globals['_ADJUSTMENTENTRYSETTING']._serialized_end=856
# @@protoc_insertion_point(module_scope)
