# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: api/aws/calculator.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x18\x61pi/aws/calculator.proto\x12\x0f\x62lueapi.api.aws\"$\n\x13\x41\x64justmentsTypeList\x12\r\n\x05types\x18\x01 \x03(\t\"j\n\x18\x45xcludedServiceFromUsage\x12\x19\n\x11managementAccount\x18\x01 \x01(\t\x12\x13\n\x0bproductCode\x18\x02 \x01(\t\x12\x1e\n\x16\x63onvertedToAdjustments\x18\x03 \x01(\x08\"\xa3\x01\n\x10\x43\x61lculatorConfig\x12\x41\n\x13\x61\x64justmentsTypeList\x18\x01 \x01(\x0b\x32$.blueapi.api.aws.AdjustmentsTypeList\x12L\n\x19\x65xcludedServicesFromUsage\x18\x02 \x03(\x0b\x32).blueapi.api.aws.ExcludedServiceFromUsageBb\n\x1d\x63loud.alphaus.blueapi.api.awsB\x15\x41piAwsCalculatorProtoZ*github.com/alphauslabs/blue-sdk-go/api/awsb\x06proto3')



_ADJUSTMENTSTYPELIST = DESCRIPTOR.message_types_by_name['AdjustmentsTypeList']
_EXCLUDEDSERVICEFROMUSAGE = DESCRIPTOR.message_types_by_name['ExcludedServiceFromUsage']
_CALCULATORCONFIG = DESCRIPTOR.message_types_by_name['CalculatorConfig']
AdjustmentsTypeList = _reflection.GeneratedProtocolMessageType('AdjustmentsTypeList', (_message.Message,), {
  'DESCRIPTOR' : _ADJUSTMENTSTYPELIST,
  '__module__' : 'api.aws.calculator_pb2'
  # @@protoc_insertion_point(class_scope:blueapi.api.aws.AdjustmentsTypeList)
  })
_sym_db.RegisterMessage(AdjustmentsTypeList)

ExcludedServiceFromUsage = _reflection.GeneratedProtocolMessageType('ExcludedServiceFromUsage', (_message.Message,), {
  'DESCRIPTOR' : _EXCLUDEDSERVICEFROMUSAGE,
  '__module__' : 'api.aws.calculator_pb2'
  # @@protoc_insertion_point(class_scope:blueapi.api.aws.ExcludedServiceFromUsage)
  })
_sym_db.RegisterMessage(ExcludedServiceFromUsage)

CalculatorConfig = _reflection.GeneratedProtocolMessageType('CalculatorConfig', (_message.Message,), {
  'DESCRIPTOR' : _CALCULATORCONFIG,
  '__module__' : 'api.aws.calculator_pb2'
  # @@protoc_insertion_point(class_scope:blueapi.api.aws.CalculatorConfig)
  })
_sym_db.RegisterMessage(CalculatorConfig)

if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\n\035cloud.alphaus.blueapi.api.awsB\025ApiAwsCalculatorProtoZ*github.com/alphauslabs/blue-sdk-go/api/aws'
  _ADJUSTMENTSTYPELIST._serialized_start=45
  _ADJUSTMENTSTYPELIST._serialized_end=81
  _EXCLUDEDSERVICEFROMUSAGE._serialized_start=83
  _EXCLUDEDSERVICEFROMUSAGE._serialized_end=189
  _CALCULATORCONFIG._serialized_start=192
  _CALCULATORCONFIG._serialized_end=355
# @@protoc_insertion_point(module_scope)
