# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: api/pricing/details.proto
# Protobuf Python Version: 5.26.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x19\x61pi/pricing/details.proto\x12\x13\x62lueapi.api.pricing\"\x94\x02\n\x0bPricingData\x12\x0e\n\x06vendor\x18\x01 \x01(\t\x12\x0f\n\x07service\x18\x02 \x01(\t\x12\x12\n\nregionCode\x18\x03 \x01(\t\x12\x0b\n\x03sku\x18\x04 \x01(\t\x12\x0c\n\x04unit\x18\x05 \x01(\t\x12\x14\n\x0cpricePerUnit\x18\x06 \x01(\x01\x12L\n\x0eserviceDetails\x18\x07 \x03(\x0b\x32\x34.blueapi.api.pricing.PricingData.ServiceDetailsEntry\x1aQ\n\x13ServiceDetailsEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12)\n\x05value\x18\x02 \x01(\x0b\x32\x1a.blueapi.api.pricing.Value:\x02\x38\x01\"6\n\x05Value\x12\x10\n\x06strVal\x18\x01 \x01(\tH\x00\x12\x12\n\x08\x66loatVal\x18\x02 \x01(\x02H\x00\x42\x07\n\x05valueBk\n!cloud.alphaus.blueapi.api.pricingB\x16\x41piPricingDetailsProtoZ.github.com/alphauslabs/blue-sdk-go/api/pricingb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'api.pricing.details_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n!cloud.alphaus.blueapi.api.pricingB\026ApiPricingDetailsProtoZ.github.com/alphauslabs/blue-sdk-go/api/pricing'
  _globals['_PRICINGDATA_SERVICEDETAILSENTRY']._loaded_options = None
  _globals['_PRICINGDATA_SERVICEDETAILSENTRY']._serialized_options = b'8\001'
  _globals['_PRICINGDATA']._serialized_start=51
  _globals['_PRICINGDATA']._serialized_end=327
  _globals['_PRICINGDATA_SERVICEDETAILSENTRY']._serialized_start=246
  _globals['_PRICINGDATA_SERVICEDETAILSENTRY']._serialized_end=327
  _globals['_VALUE']._serialized_start=329
  _globals['_VALUE']._serialized_end=383
# @@protoc_insertion_point(module_scope)
