# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: api/cover/asset.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x15\x61pi/cover/asset.proto\x12\x11\x62lueapi.api.cover\"\x85\x01\n\x05\x41sset\x12\x0b\n\x03key\x18\x01 \x01(\t\x12<\n\nattributes\x18\x02 \x03(\x0b\x32(.blueapi.api.cover.Asset.AttributesEntry\x1a\x31\n\x0f\x41ttributesEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01\"\xed\x01\n\x0f\x44iscoverRequest\x12\x11\n\trequestId\x18\x01 \x01(\t\x12\r\n\x05orgId\x18\x02 \x01(\t\x12\x19\n\x11\x64\x61tetimeRequested\x18\x03 \x01(\t\x12\x0e\n\x06status\x18\x04 \x01(\t\x12\x12\n\nlastUpdate\x18\x05 \x01(\t\x12\x46\n\nattributes\x18\x06 \x03(\x0b\x32\x32.blueapi.api.cover.DiscoverRequest.AttributesEntry\x1a\x31\n\x0f\x41ttributesEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01\x42\x63\n\x1f\x63loud.alphaus.blueapi.api.coverB\x12\x41piCoverAssetProtoZ,github.com/alphauslabs/blue-sdk-go/api/coverb\x06proto3')



_ASSET = DESCRIPTOR.message_types_by_name['Asset']
_ASSET_ATTRIBUTESENTRY = _ASSET.nested_types_by_name['AttributesEntry']
_DISCOVERREQUEST = DESCRIPTOR.message_types_by_name['DiscoverRequest']
_DISCOVERREQUEST_ATTRIBUTESENTRY = _DISCOVERREQUEST.nested_types_by_name['AttributesEntry']
Asset = _reflection.GeneratedProtocolMessageType('Asset', (_message.Message,), {

  'AttributesEntry' : _reflection.GeneratedProtocolMessageType('AttributesEntry', (_message.Message,), {
    'DESCRIPTOR' : _ASSET_ATTRIBUTESENTRY,
    '__module__' : 'api.cover.asset_pb2'
    # @@protoc_insertion_point(class_scope:blueapi.api.cover.Asset.AttributesEntry)
    })
  ,
  'DESCRIPTOR' : _ASSET,
  '__module__' : 'api.cover.asset_pb2'
  # @@protoc_insertion_point(class_scope:blueapi.api.cover.Asset)
  })
_sym_db.RegisterMessage(Asset)
_sym_db.RegisterMessage(Asset.AttributesEntry)

DiscoverRequest = _reflection.GeneratedProtocolMessageType('DiscoverRequest', (_message.Message,), {

  'AttributesEntry' : _reflection.GeneratedProtocolMessageType('AttributesEntry', (_message.Message,), {
    'DESCRIPTOR' : _DISCOVERREQUEST_ATTRIBUTESENTRY,
    '__module__' : 'api.cover.asset_pb2'
    # @@protoc_insertion_point(class_scope:blueapi.api.cover.DiscoverRequest.AttributesEntry)
    })
  ,
  'DESCRIPTOR' : _DISCOVERREQUEST,
  '__module__' : 'api.cover.asset_pb2'
  # @@protoc_insertion_point(class_scope:blueapi.api.cover.DiscoverRequest)
  })
_sym_db.RegisterMessage(DiscoverRequest)
_sym_db.RegisterMessage(DiscoverRequest.AttributesEntry)

if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\n\037cloud.alphaus.blueapi.api.coverB\022ApiCoverAssetProtoZ,github.com/alphauslabs/blue-sdk-go/api/cover'
  _ASSET_ATTRIBUTESENTRY._options = None
  _ASSET_ATTRIBUTESENTRY._serialized_options = b'8\001'
  _DISCOVERREQUEST_ATTRIBUTESENTRY._options = None
  _DISCOVERREQUEST_ATTRIBUTESENTRY._serialized_options = b'8\001'
  _ASSET._serialized_start=45
  _ASSET._serialized_end=178
  _ASSET_ATTRIBUTESENTRY._serialized_start=129
  _ASSET_ATTRIBUTESENTRY._serialized_end=178
  _DISCOVERREQUEST._serialized_start=181
  _DISCOVERREQUEST._serialized_end=418
  _DISCOVERREQUEST_ATTRIBUTESENTRY._serialized_start=129
  _DISCOVERREQUEST_ATTRIBUTESENTRY._serialized_end=178
# @@protoc_insertion_point(module_scope)
