# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: api/cover/budget.proto
# Protobuf Python Version: 4.25.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from alphausblue.api.cover import alert_pb2 as api_dot_cover_dot_alert__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x16\x61pi/cover/budget.proto\x12\x11\x62lueapi.api.cover\x1a\x15\x61pi/cover/alert.proto\"\xb2\x02\n\nBudgetData\x12\n\n\x02id\x18\x01 \x01(\t\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\x13\n\x0b\x64\x65scription\x18\x03 \x01(\t\x12\x13\n\x0bgranularity\x18\x04 \x01(\t\x12\x11\n\tstartDate\x18\x05 \x01(\t\x12\x0f\n\x07\x65ndDate\x18\x06 \x01(\t\x12\x13\n\x0btotalBudget\x18\x07 \x01(\x02\x12=\n\x0egranularBudget\x18\x08 \x03(\x0b\x32%.blueapi.api.cover.GranularBudgetData\x12\x34\n\tcostGroup\x18\t \x01(\x0b\x32!.blueapi.api.cover.AlertCostGroup\x12\x32\n\x08\x63hannels\x18\n \x01(\x0b\x32 .blueapi.api.cover.AlertChannels\"4\n\x12GranularBudgetData\x12\x0e\n\x06period\x18\x01 \x01(\t\x12\x0e\n\x06\x62udget\x18\x02 \x01(\x02\x42\x64\n\x1f\x63loud.alphaus.blueapi.api.coverB\x13\x41piCoverBudgetProtoZ,github.com/alphauslabs/blue-sdk-go/api/coverb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'api.cover.budget_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  _globals['DESCRIPTOR']._options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\037cloud.alphaus.blueapi.api.coverB\023ApiCoverBudgetProtoZ,github.com/alphauslabs/blue-sdk-go/api/cover'
  _globals['_BUDGETDATA']._serialized_start=69
  _globals['_BUDGETDATA']._serialized_end=375
  _globals['_GRANULARBUDGETDATA']._serialized_start=377
  _globals['_GRANULARBUDGETDATA']._serialized_end=429
# @@protoc_insertion_point(module_scope)
