# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: api/cover/costforecast.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'api/cover/costforecast.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1c\x61pi/cover/costforecast.proto\x12\x11\x62lueapi.api.cover\"\xcc\x01\n\x0f\x41wsCostForecast\x12\x0c\n\x04\x64\x61te\x18\x01 \x01(\t\x12\x0f\n\x07\x61\x63\x63ount\x18\x02 \x01(\t\x12\x13\n\x0bproductCode\x18\x03 \x01(\t\x12\x0c\n\x04\x63ost\x18\x04 \x01(\x01\x12\x12\n\nlowerBound\x18\x05 \x01(\x01\x12\x12\n\nupperBound\x18\x06 \x01(\x01\x12\x15\n\runblendedCost\x18\x07 \x01(\x01\x12\x1b\n\x13unblendedLowerBound\x18\x08 \x01(\x01\x12\x1b\n\x13unblendedUpperBound\x18\t \x01(\x01\"%\n\tCostGroup\x12\n\n\x02id\x18\x01 \x01(\t\x12\x0c\n\x04name\x18\x02 \x01(\t\"\xe3\x01\n\x13\x43ostForecastDetails\x12\n\n\x02id\x18\x01 \x01(\t\x12\x14\n\x0c\x66orecastName\x18\x02 \x01(\t\x12\x13\n\x0b\x64\x65scription\x18\x03 \x01(\t\x12/\n\tcostgroup\x18\x04 \x01(\x0b\x32\x1c.blueapi.api.cover.CostGroup\x12\x11\n\tstartDate\x18\x05 \x01(\t\x12\x0f\n\x07\x65ndDate\x18\x06 \x01(\t\x12\x11\n\tcreatedBy\x18\x07 \x01(\t\x12\x14\n\x0c\x63reationDate\x18\x08 \x01(\t\x12\x17\n\x0flastUpdatedDate\x18\t \x01(\t\"\x83\x01\n\x12\x45xternalAdjustment\x12\n\n\x02id\x18\x01 \x01(\t\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\x13\n\x0b\x64\x65scription\x18\x03 \x01(\t\x12>\n\x0b\x61\x64justments\x18\x04 \x03(\x0b\x32).blueapi.api.cover.CostForecastAdjustment\";\n\x16\x43ostForecastAdjustment\x12\r\n\x05month\x18\x01 \x01(\t\x12\x12\n\nadjustment\x18\x02 \x01(\x01\x42j\n\x1f\x63loud.alphaus.blueapi.api.coverB\x19\x41piCoverCostForecastProtoZ,github.com/alphauslabs/blue-sdk-go/api/coverb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'api.cover.costforecast_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\037cloud.alphaus.blueapi.api.coverB\031ApiCoverCostForecastProtoZ,github.com/alphauslabs/blue-sdk-go/api/cover'
  _globals['_AWSCOSTFORECAST']._serialized_start=52
  _globals['_AWSCOSTFORECAST']._serialized_end=256
  _globals['_COSTGROUP']._serialized_start=258
  _globals['_COSTGROUP']._serialized_end=295
  _globals['_COSTFORECASTDETAILS']._serialized_start=298
  _globals['_COSTFORECASTDETAILS']._serialized_end=525
  _globals['_EXTERNALADJUSTMENT']._serialized_start=528
  _globals['_EXTERNALADJUSTMENT']._serialized_end=659
  _globals['_COSTFORECASTADJUSTMENT']._serialized_start=661
  _globals['_COSTFORECASTADJUSTMENT']._serialized_end=720
# @@protoc_insertion_point(module_scope)
