# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: api/cover/costforecast.proto
# Protobuf Python Version: 5.26.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1c\x61pi/cover/costforecast.proto\x12\x11\x62lueapi.api.cover\"\xcc\x01\n\x0f\x41wsCostForecast\x12\x0c\n\x04\x64\x61te\x18\x01 \x01(\t\x12\x0f\n\x07\x61\x63\x63ount\x18\x02 \x01(\t\x12\x13\n\x0bproductCode\x18\x03 \x01(\t\x12\x0c\n\x04\x63ost\x18\x04 \x01(\x01\x12\x12\n\nlowerBound\x18\x05 \x01(\x01\x12\x12\n\nupperBound\x18\x06 \x01(\x01\x12\x15\n\runblendedCost\x18\x07 \x01(\x01\x12\x1b\n\x13unblendedLowerBound\x18\x08 \x01(\x01\x12\x1b\n\x13unblendedUpperBound\x18\t \x01(\x01\x42j\n\x1f\x63loud.alphaus.blueapi.api.coverB\x19\x41piCoverCostForecastProtoZ,github.com/alphauslabs/blue-sdk-go/api/coverb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'api.cover.costforecast_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\037cloud.alphaus.blueapi.api.coverB\031ApiCoverCostForecastProtoZ,github.com/alphauslabs/blue-sdk-go/api/cover'
  _globals['_AWSCOSTFORECAST']._serialized_start=52
  _globals['_AWSCOSTFORECAST']._serialized_end=256
# @@protoc_insertion_point(module_scope)
