# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: api/keyvalue.proto
# Protobuf Python Version: 5.28.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    28,
    1,
    '',
    'api/keyvalue.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x12\x61pi/keyvalue.proto\x12\x0b\x62lueapi.api\"&\n\x08KeyValue\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t\"O\n\x0bKeyValueMap\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\x15\n\x0bstringValue\x18\x02 \x01(\tH\x00\x12\x13\n\tboolValue\x18\x03 \x01(\x08H\x00\x42\x07\n\x05valueBU\n\x19\x63loud.alphaus.blueapi.apiB\x10\x41piKeyValueProtoZ&github.com/alphauslabs/blue-sdk-go/apib\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'api.keyvalue_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\031cloud.alphaus.blueapi.apiB\020ApiKeyValueProtoZ&github.com/alphauslabs/blue-sdk-go/api'
  _globals['_KEYVALUE']._serialized_start=35
  _globals['_KEYVALUE']._serialized_end=73
  _globals['_KEYVALUEMAP']._serialized_start=75
  _globals['_KEYVALUEMAP']._serialized_end=154
# @@protoc_insertion_point(module_scope)
