# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: api/rbac.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0e\x61pi/rbac.proto\x12\x0b\x62lueapi.api\"E\n\x06Policy\x12\x0e\n\x06\x61\x63tion\x18\x01 \x01(\t\x12\x0e\n\x06\x65\x66\x66\x65\x63t\x18\x02 \x01(\t\x12\x0b\n\x03key\x18\x03 \x01(\t\x12\x0e\n\x06values\x18\x04 \x03(\t\"[\n\nPermission\x12\x11\n\tnamespace\x18\x01 \x01(\t\x12\x13\n\x0bpermissions\x18\x02 \x03(\t\x12%\n\x08policies\x18\x03 \x03(\x0b\x32\x13.blueapi.api.Policy\"c\n\x04Role\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x11\n\tnamespace\x18\x02 \x01(\t\x12\x13\n\x0bpermissions\x18\x03 \x03(\t\x12%\n\x08policies\x18\x04 \x03(\x0b\x32\x13.blueapi.api.Policy\"e\n\x0fUserRoleMapping\x12\x10\n\x08rootUser\x18\x01 \x01(\t\x12\x0f\n\x07subUser\x18\x02 \x01(\t\x12\x11\n\tnamespace\x18\x03 \x01(\t\x12\x0c\n\x04role\x18\x04 \x01(\t\x12\x0e\n\x06\x66ilter\x18\x05 \x01(\tBQ\n\x19\x63loud.alphaus.blueapi.apiB\x0c\x41piRbacProtoZ&github.com/alphauslabs/blue-sdk-go/apib\x06proto3')



_POLICY = DESCRIPTOR.message_types_by_name['Policy']
_PERMISSION = DESCRIPTOR.message_types_by_name['Permission']
_ROLE = DESCRIPTOR.message_types_by_name['Role']
_USERROLEMAPPING = DESCRIPTOR.message_types_by_name['UserRoleMapping']
Policy = _reflection.GeneratedProtocolMessageType('Policy', (_message.Message,), {
  'DESCRIPTOR' : _POLICY,
  '__module__' : 'api.rbac_pb2'
  # @@protoc_insertion_point(class_scope:blueapi.api.Policy)
  })
_sym_db.RegisterMessage(Policy)

Permission = _reflection.GeneratedProtocolMessageType('Permission', (_message.Message,), {
  'DESCRIPTOR' : _PERMISSION,
  '__module__' : 'api.rbac_pb2'
  # @@protoc_insertion_point(class_scope:blueapi.api.Permission)
  })
_sym_db.RegisterMessage(Permission)

Role = _reflection.GeneratedProtocolMessageType('Role', (_message.Message,), {
  'DESCRIPTOR' : _ROLE,
  '__module__' : 'api.rbac_pb2'
  # @@protoc_insertion_point(class_scope:blueapi.api.Role)
  })
_sym_db.RegisterMessage(Role)

UserRoleMapping = _reflection.GeneratedProtocolMessageType('UserRoleMapping', (_message.Message,), {
  'DESCRIPTOR' : _USERROLEMAPPING,
  '__module__' : 'api.rbac_pb2'
  # @@protoc_insertion_point(class_scope:blueapi.api.UserRoleMapping)
  })
_sym_db.RegisterMessage(UserRoleMapping)

if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\n\031cloud.alphaus.blueapi.apiB\014ApiRbacProtoZ&github.com/alphauslabs/blue-sdk-go/api'
  _POLICY._serialized_start=31
  _POLICY._serialized_end=100
  _PERMISSION._serialized_start=102
  _PERMISSION._serialized_end=193
  _ROLE._serialized_start=195
  _ROLE._serialized_end=294
  _USERROLEMAPPING._serialized_start=296
  _USERROLEMAPPING._serialized_end=397
# @@protoc_insertion_point(module_scope)
