# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from alphausblue.pricing.v1 import pricing_pb2 as pricing_dot_v1_dot_pricing__pb2

GRPC_GENERATED_VERSION = '1.64.1'
GRPC_VERSION = grpc.__version__
EXPECTED_ERROR_RELEASE = '1.65.0'
SCHEDULED_RELEASE_DATE = 'June 25, 2024'
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    warnings.warn(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in pricing/v1/pricing_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
        + f' This warning will become an error in {EXPECTED_ERROR_RELEASE},'
        + f' scheduled for release on {SCHEDULED_RELEASE_DATE}.',
        RuntimeWarning
    )


class PricingStub(object):
    """Pricing service definition.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetInfo = channel.unary_unary(
                '/blueapi.pricing.v1.Pricing/GetInfo',
                request_serializer=pricing_dot_v1_dot_pricing__pb2.GetInfoRequest.SerializeToString,
                response_deserializer=pricing_dot_v1_dot_pricing__pb2.GetInfoResponse.FromString,
                _registered_method=True)
        self.GetPricingInfo = channel.unary_stream(
                '/blueapi.pricing.v1.Pricing/GetPricingInfo',
                request_serializer=pricing_dot_v1_dot_pricing__pb2.GetPricingInfoRequest.SerializeToString,
                response_deserializer=pricing_dot_v1_dot_pricing__pb2.GetPricingInfoResponse.FromString,
                _registered_method=True)


class PricingServicer(object):
    """Pricing service definition.
    """

    def GetInfo(self, request, context):
        """Test endpoint only.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetPricingInfo(self, request, context):
        """Get pricing info
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_PricingServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetInfo': grpc.unary_unary_rpc_method_handler(
                    servicer.GetInfo,
                    request_deserializer=pricing_dot_v1_dot_pricing__pb2.GetInfoRequest.FromString,
                    response_serializer=pricing_dot_v1_dot_pricing__pb2.GetInfoResponse.SerializeToString,
            ),
            'GetPricingInfo': grpc.unary_stream_rpc_method_handler(
                    servicer.GetPricingInfo,
                    request_deserializer=pricing_dot_v1_dot_pricing__pb2.GetPricingInfoRequest.FromString,
                    response_serializer=pricing_dot_v1_dot_pricing__pb2.GetPricingInfoResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'blueapi.pricing.v1.Pricing', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('blueapi.pricing.v1.Pricing', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class Pricing(object):
    """Pricing service definition.
    """

    @staticmethod
    def GetInfo(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/blueapi.pricing.v1.Pricing/GetInfo',
            pricing_dot_v1_dot_pricing__pb2.GetInfoRequest.SerializeToString,
            pricing_dot_v1_dot_pricing__pb2.GetInfoResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetPricingInfo(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/blueapi.pricing.v1.Pricing/GetPricingInfo',
            pricing_dot_v1_dot_pricing__pb2.GetPricingInfoRequest.SerializeToString,
            pricing_dot_v1_dot_pricing__pb2.GetPricingInfoResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
