# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2
from alphausblue.prism.v1 import prism_pb2 as prism_dot_v1_dot_prism__pb2

GRPC_GENERATED_VERSION = '1.75.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in prism/v1/prism_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class PrismStub(object):
    """Prism service definition.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Test = channel.unary_unary(
                '/blueapi.prism.v1.Prism/Test',
                request_serializer=prism_dot_v1_dot_prism__pb2.TestRequest.SerializeToString,
                response_deserializer=prism_dot_v1_dot_prism__pb2.TestResponse.FromString,
                _registered_method=True)
        self.CreateProject = channel.unary_unary(
                '/blueapi.prism.v1.Prism/CreateProject',
                request_serializer=prism_dot_v1_dot_prism__pb2.CreateProjectRequest.SerializeToString,
                response_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                _registered_method=True)
        self.GetProject = channel.unary_unary(
                '/blueapi.prism.v1.Prism/GetProject',
                request_serializer=prism_dot_v1_dot_prism__pb2.GetProjectRequest.SerializeToString,
                response_deserializer=prism_dot_v1_dot_prism__pb2.GetProjectResponse.FromString,
                _registered_method=True)
        self.DeleteProject = channel.unary_unary(
                '/blueapi.prism.v1.Prism/DeleteProject',
                request_serializer=prism_dot_v1_dot_prism__pb2.DeleteProjectRequest.SerializeToString,
                response_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                _registered_method=True)
        self.ListProjects = channel.unary_stream(
                '/blueapi.prism.v1.Prism/ListProjects',
                request_serializer=prism_dot_v1_dot_prism__pb2.ListProjectsRequest.SerializeToString,
                response_deserializer=prism_dot_v1_dot_prism__pb2.Project.FromString,
                _registered_method=True)
        self.CreateOrganization = channel.unary_unary(
                '/blueapi.prism.v1.Prism/CreateOrganization',
                request_serializer=prism_dot_v1_dot_prism__pb2.CreateOrganizationRequest.SerializeToString,
                response_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                _registered_method=True)
        self.GetOrganization = channel.unary_unary(
                '/blueapi.prism.v1.Prism/GetOrganization',
                request_serializer=prism_dot_v1_dot_prism__pb2.GetOrganizationRequest.SerializeToString,
                response_deserializer=prism_dot_v1_dot_prism__pb2.GetOrganizationResponse.FromString,
                _registered_method=True)
        self.UpdateOrganization = channel.unary_unary(
                '/blueapi.prism.v1.Prism/UpdateOrganization',
                request_serializer=prism_dot_v1_dot_prism__pb2.UpdateOrganizationRequest.SerializeToString,
                response_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                _registered_method=True)
        self.DeleteOrganization = channel.unary_unary(
                '/blueapi.prism.v1.Prism/DeleteOrganization',
                request_serializer=prism_dot_v1_dot_prism__pb2.DeleteOrganizationRequest.SerializeToString,
                response_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                _registered_method=True)
        self.VerifyUser = channel.unary_unary(
                '/blueapi.prism.v1.Prism/VerifyUser',
                request_serializer=prism_dot_v1_dot_prism__pb2.VerifyUserRequest.SerializeToString,
                response_deserializer=prism_dot_v1_dot_prism__pb2.VerifyUserResponse.FromString,
                _registered_method=True)
        self.CreateTeam = channel.unary_unary(
                '/blueapi.prism.v1.Prism/CreateTeam',
                request_serializer=prism_dot_v1_dot_prism__pb2.CreateTeamRequest.SerializeToString,
                response_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                _registered_method=True)
        self.GetTeam = channel.unary_unary(
                '/blueapi.prism.v1.Prism/GetTeam',
                request_serializer=prism_dot_v1_dot_prism__pb2.GetTeamRequest.SerializeToString,
                response_deserializer=prism_dot_v1_dot_prism__pb2.GetTeamResponse.FromString,
                _registered_method=True)
        self.ListTeams = channel.unary_stream(
                '/blueapi.prism.v1.Prism/ListTeams',
                request_serializer=prism_dot_v1_dot_prism__pb2.ListTeamsRequest.SerializeToString,
                response_deserializer=prism_dot_v1_dot_prism__pb2.Team.FromString,
                _registered_method=True)
        self.ListTeamMembers = channel.unary_stream(
                '/blueapi.prism.v1.Prism/ListTeamMembers',
                request_serializer=prism_dot_v1_dot_prism__pb2.ListTeamMembersRequest.SerializeToString,
                response_deserializer=prism_dot_v1_dot_prism__pb2.Member.FromString,
                _registered_method=True)
        self.ListProjectToTeam = channel.unary_stream(
                '/blueapi.prism.v1.Prism/ListProjectToTeam',
                request_serializer=prism_dot_v1_dot_prism__pb2.ListProjectToTeamRequest.SerializeToString,
                response_deserializer=prism_dot_v1_dot_prism__pb2.ListProjectToTeamResponse.FromString,
                _registered_method=True)
        self.ListProducts = channel.unary_stream(
                '/blueapi.prism.v1.Prism/ListProducts',
                request_serializer=prism_dot_v1_dot_prism__pb2.ListProductsRequest.SerializeToString,
                response_deserializer=prism_dot_v1_dot_prism__pb2.Product.FromString,
                _registered_method=True)
        self.CreateProduct = channel.unary_unary(
                '/blueapi.prism.v1.Prism/CreateProduct',
                request_serializer=prism_dot_v1_dot_prism__pb2.CreateProductRequest.SerializeToString,
                response_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                _registered_method=True)
        self.DeleteProduct = channel.unary_unary(
                '/blueapi.prism.v1.Prism/DeleteProduct',
                request_serializer=prism_dot_v1_dot_prism__pb2.DeleteProductRequest.SerializeToString,
                response_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                _registered_method=True)
        self.AssignProjectToTeam = channel.unary_unary(
                '/blueapi.prism.v1.Prism/AssignProjectToTeam',
                request_serializer=prism_dot_v1_dot_prism__pb2.AssignProjectToTeamRequest.SerializeToString,
                response_deserializer=prism_dot_v1_dot_prism__pb2.AssignProjectToTeamResponse.FromString,
                _registered_method=True)
        self.DeleteTeam = channel.unary_unary(
                '/blueapi.prism.v1.Prism/DeleteTeam',
                request_serializer=prism_dot_v1_dot_prism__pb2.DeleteTeamRequest.SerializeToString,
                response_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                _registered_method=True)
        self.GetIntegrationStatus = channel.unary_unary(
                '/blueapi.prism.v1.Prism/GetIntegrationStatus',
                request_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
                response_deserializer=prism_dot_v1_dot_prism__pb2.GetIntegrationStatusResponse.FromString,
                _registered_method=True)
        self.ListReportSchedules = channel.unary_stream(
                '/blueapi.prism.v1.Prism/ListReportSchedules',
                request_serializer=prism_dot_v1_dot_prism__pb2.ListReportSchedulesRequest.SerializeToString,
                response_deserializer=prism_dot_v1_dot_prism__pb2.ReportSchedule.FromString,
                _registered_method=True)
        self.UpdateReportSchedule = channel.unary_unary(
                '/blueapi.prism.v1.Prism/UpdateReportSchedule',
                request_serializer=prism_dot_v1_dot_prism__pb2.ReportSchedule.SerializeToString,
                response_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                _registered_method=True)
        self.CreateReportSchedule = channel.unary_unary(
                '/blueapi.prism.v1.Prism/CreateReportSchedule',
                request_serializer=prism_dot_v1_dot_prism__pb2.ReportSchedule.SerializeToString,
                response_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                _registered_method=True)
        self.UpdateOrgTimezone = channel.unary_unary(
                '/blueapi.prism.v1.Prism/UpdateOrgTimezone',
                request_serializer=prism_dot_v1_dot_prism__pb2.UpdateOrgTimezoneRequest.SerializeToString,
                response_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                _registered_method=True)
        self.ListIntegrationStatus = channel.unary_stream(
                '/blueapi.prism.v1.Prism/ListIntegrationStatus',
                request_serializer=prism_dot_v1_dot_prism__pb2.ListIntegrationStatusRequest.SerializeToString,
                response_deserializer=prism_dot_v1_dot_prism__pb2.IntegrationStatus.FromString,
                _registered_method=True)
        self.UpdateWorkflow = channel.unary_unary(
                '/blueapi.prism.v1.Prism/UpdateWorkflow',
                request_serializer=prism_dot_v1_dot_prism__pb2.UpdateWorkflowRequest.SerializeToString,
                response_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                _registered_method=True)
        self.ListWorkflows = channel.unary_stream(
                '/blueapi.prism.v1.Prism/ListWorkflows',
                request_serializer=prism_dot_v1_dot_prism__pb2.ListWorkflowsRequest.SerializeToString,
                response_deserializer=prism_dot_v1_dot_prism__pb2.Workflow.FromString,
                _registered_method=True)
        self.ListActivities = channel.unary_stream(
                '/blueapi.prism.v1.Prism/ListActivities',
                request_serializer=prism_dot_v1_dot_prism__pb2.ListActivitiesRequest.SerializeToString,
                response_deserializer=prism_dot_v1_dot_prism__pb2.Activity.FromString,
                _registered_method=True)
        self.JoinOrganization = channel.unary_unary(
                '/blueapi.prism.v1.Prism/JoinOrganization',
                request_serializer=prism_dot_v1_dot_prism__pb2.JoinOrganizationRequest.SerializeToString,
                response_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                _registered_method=True)
        self.GenerateOrganizationCode = channel.unary_unary(
                '/blueapi.prism.v1.Prism/GenerateOrganizationCode',
                request_serializer=prism_dot_v1_dot_prism__pb2.GenerateOrganizationCodeRequest.SerializeToString,
                response_deserializer=prism_dot_v1_dot_prism__pb2.GenerateOrganizationCodeResponse.FromString,
                _registered_method=True)
        self.ShareGDrive = channel.unary_unary(
                '/blueapi.prism.v1.Prism/ShareGDrive',
                request_serializer=prism_dot_v1_dot_prism__pb2.ShareGDriveRequest.SerializeToString,
                response_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                _registered_method=True)


class PrismServicer(object):
    """Prism service definition.
    """

    def Test(self, request, context):
        """Test endpoint only.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CreateProject(self, request, context):
        """WIP: Creates a new project.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetProject(self, request, context):
        """WIP: Gets information about a project by ID.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeleteProject(self, request, context):
        """WIP: Deletes a project by ID.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListProjects(self, request, context):
        """WIP: Lists all projects 
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CreateOrganization(self, request, context):
        """Creates a new organization.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetOrganization(self, request, context):
        """Gets information about an organization by ID.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdateOrganization(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeleteOrganization(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def VerifyUser(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CreateTeam(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetTeam(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListTeams(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListTeamMembers(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListProjectToTeam(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListProducts(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CreateProduct(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeleteProduct(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def AssignProjectToTeam(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeleteTeam(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetIntegrationStatus(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListReportSchedules(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdateReportSchedule(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CreateReportSchedule(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdateOrgTimezone(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListIntegrationStatus(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdateWorkflow(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListWorkflows(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListActivities(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def JoinOrganization(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GenerateOrganizationCode(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ShareGDrive(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_PrismServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Test': grpc.unary_unary_rpc_method_handler(
                    servicer.Test,
                    request_deserializer=prism_dot_v1_dot_prism__pb2.TestRequest.FromString,
                    response_serializer=prism_dot_v1_dot_prism__pb2.TestResponse.SerializeToString,
            ),
            'CreateProject': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateProject,
                    request_deserializer=prism_dot_v1_dot_prism__pb2.CreateProjectRequest.FromString,
                    response_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            ),
            'GetProject': grpc.unary_unary_rpc_method_handler(
                    servicer.GetProject,
                    request_deserializer=prism_dot_v1_dot_prism__pb2.GetProjectRequest.FromString,
                    response_serializer=prism_dot_v1_dot_prism__pb2.GetProjectResponse.SerializeToString,
            ),
            'DeleteProject': grpc.unary_unary_rpc_method_handler(
                    servicer.DeleteProject,
                    request_deserializer=prism_dot_v1_dot_prism__pb2.DeleteProjectRequest.FromString,
                    response_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            ),
            'ListProjects': grpc.unary_stream_rpc_method_handler(
                    servicer.ListProjects,
                    request_deserializer=prism_dot_v1_dot_prism__pb2.ListProjectsRequest.FromString,
                    response_serializer=prism_dot_v1_dot_prism__pb2.Project.SerializeToString,
            ),
            'CreateOrganization': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateOrganization,
                    request_deserializer=prism_dot_v1_dot_prism__pb2.CreateOrganizationRequest.FromString,
                    response_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            ),
            'GetOrganization': grpc.unary_unary_rpc_method_handler(
                    servicer.GetOrganization,
                    request_deserializer=prism_dot_v1_dot_prism__pb2.GetOrganizationRequest.FromString,
                    response_serializer=prism_dot_v1_dot_prism__pb2.GetOrganizationResponse.SerializeToString,
            ),
            'UpdateOrganization': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdateOrganization,
                    request_deserializer=prism_dot_v1_dot_prism__pb2.UpdateOrganizationRequest.FromString,
                    response_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            ),
            'DeleteOrganization': grpc.unary_unary_rpc_method_handler(
                    servicer.DeleteOrganization,
                    request_deserializer=prism_dot_v1_dot_prism__pb2.DeleteOrganizationRequest.FromString,
                    response_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            ),
            'VerifyUser': grpc.unary_unary_rpc_method_handler(
                    servicer.VerifyUser,
                    request_deserializer=prism_dot_v1_dot_prism__pb2.VerifyUserRequest.FromString,
                    response_serializer=prism_dot_v1_dot_prism__pb2.VerifyUserResponse.SerializeToString,
            ),
            'CreateTeam': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateTeam,
                    request_deserializer=prism_dot_v1_dot_prism__pb2.CreateTeamRequest.FromString,
                    response_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            ),
            'GetTeam': grpc.unary_unary_rpc_method_handler(
                    servicer.GetTeam,
                    request_deserializer=prism_dot_v1_dot_prism__pb2.GetTeamRequest.FromString,
                    response_serializer=prism_dot_v1_dot_prism__pb2.GetTeamResponse.SerializeToString,
            ),
            'ListTeams': grpc.unary_stream_rpc_method_handler(
                    servicer.ListTeams,
                    request_deserializer=prism_dot_v1_dot_prism__pb2.ListTeamsRequest.FromString,
                    response_serializer=prism_dot_v1_dot_prism__pb2.Team.SerializeToString,
            ),
            'ListTeamMembers': grpc.unary_stream_rpc_method_handler(
                    servicer.ListTeamMembers,
                    request_deserializer=prism_dot_v1_dot_prism__pb2.ListTeamMembersRequest.FromString,
                    response_serializer=prism_dot_v1_dot_prism__pb2.Member.SerializeToString,
            ),
            'ListProjectToTeam': grpc.unary_stream_rpc_method_handler(
                    servicer.ListProjectToTeam,
                    request_deserializer=prism_dot_v1_dot_prism__pb2.ListProjectToTeamRequest.FromString,
                    response_serializer=prism_dot_v1_dot_prism__pb2.ListProjectToTeamResponse.SerializeToString,
            ),
            'ListProducts': grpc.unary_stream_rpc_method_handler(
                    servicer.ListProducts,
                    request_deserializer=prism_dot_v1_dot_prism__pb2.ListProductsRequest.FromString,
                    response_serializer=prism_dot_v1_dot_prism__pb2.Product.SerializeToString,
            ),
            'CreateProduct': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateProduct,
                    request_deserializer=prism_dot_v1_dot_prism__pb2.CreateProductRequest.FromString,
                    response_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            ),
            'DeleteProduct': grpc.unary_unary_rpc_method_handler(
                    servicer.DeleteProduct,
                    request_deserializer=prism_dot_v1_dot_prism__pb2.DeleteProductRequest.FromString,
                    response_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            ),
            'AssignProjectToTeam': grpc.unary_unary_rpc_method_handler(
                    servicer.AssignProjectToTeam,
                    request_deserializer=prism_dot_v1_dot_prism__pb2.AssignProjectToTeamRequest.FromString,
                    response_serializer=prism_dot_v1_dot_prism__pb2.AssignProjectToTeamResponse.SerializeToString,
            ),
            'DeleteTeam': grpc.unary_unary_rpc_method_handler(
                    servicer.DeleteTeam,
                    request_deserializer=prism_dot_v1_dot_prism__pb2.DeleteTeamRequest.FromString,
                    response_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            ),
            'GetIntegrationStatus': grpc.unary_unary_rpc_method_handler(
                    servicer.GetIntegrationStatus,
                    request_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                    response_serializer=prism_dot_v1_dot_prism__pb2.GetIntegrationStatusResponse.SerializeToString,
            ),
            'ListReportSchedules': grpc.unary_stream_rpc_method_handler(
                    servicer.ListReportSchedules,
                    request_deserializer=prism_dot_v1_dot_prism__pb2.ListReportSchedulesRequest.FromString,
                    response_serializer=prism_dot_v1_dot_prism__pb2.ReportSchedule.SerializeToString,
            ),
            'UpdateReportSchedule': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdateReportSchedule,
                    request_deserializer=prism_dot_v1_dot_prism__pb2.ReportSchedule.FromString,
                    response_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            ),
            'CreateReportSchedule': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateReportSchedule,
                    request_deserializer=prism_dot_v1_dot_prism__pb2.ReportSchedule.FromString,
                    response_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            ),
            'UpdateOrgTimezone': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdateOrgTimezone,
                    request_deserializer=prism_dot_v1_dot_prism__pb2.UpdateOrgTimezoneRequest.FromString,
                    response_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            ),
            'ListIntegrationStatus': grpc.unary_stream_rpc_method_handler(
                    servicer.ListIntegrationStatus,
                    request_deserializer=prism_dot_v1_dot_prism__pb2.ListIntegrationStatusRequest.FromString,
                    response_serializer=prism_dot_v1_dot_prism__pb2.IntegrationStatus.SerializeToString,
            ),
            'UpdateWorkflow': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdateWorkflow,
                    request_deserializer=prism_dot_v1_dot_prism__pb2.UpdateWorkflowRequest.FromString,
                    response_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            ),
            'ListWorkflows': grpc.unary_stream_rpc_method_handler(
                    servicer.ListWorkflows,
                    request_deserializer=prism_dot_v1_dot_prism__pb2.ListWorkflowsRequest.FromString,
                    response_serializer=prism_dot_v1_dot_prism__pb2.Workflow.SerializeToString,
            ),
            'ListActivities': grpc.unary_stream_rpc_method_handler(
                    servicer.ListActivities,
                    request_deserializer=prism_dot_v1_dot_prism__pb2.ListActivitiesRequest.FromString,
                    response_serializer=prism_dot_v1_dot_prism__pb2.Activity.SerializeToString,
            ),
            'JoinOrganization': grpc.unary_unary_rpc_method_handler(
                    servicer.JoinOrganization,
                    request_deserializer=prism_dot_v1_dot_prism__pb2.JoinOrganizationRequest.FromString,
                    response_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            ),
            'GenerateOrganizationCode': grpc.unary_unary_rpc_method_handler(
                    servicer.GenerateOrganizationCode,
                    request_deserializer=prism_dot_v1_dot_prism__pb2.GenerateOrganizationCodeRequest.FromString,
                    response_serializer=prism_dot_v1_dot_prism__pb2.GenerateOrganizationCodeResponse.SerializeToString,
            ),
            'ShareGDrive': grpc.unary_unary_rpc_method_handler(
                    servicer.ShareGDrive,
                    request_deserializer=prism_dot_v1_dot_prism__pb2.ShareGDriveRequest.FromString,
                    response_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'blueapi.prism.v1.Prism', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('blueapi.prism.v1.Prism', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class Prism(object):
    """Prism service definition.
    """

    @staticmethod
    def Test(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/blueapi.prism.v1.Prism/Test',
            prism_dot_v1_dot_prism__pb2.TestRequest.SerializeToString,
            prism_dot_v1_dot_prism__pb2.TestResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CreateProject(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/blueapi.prism.v1.Prism/CreateProject',
            prism_dot_v1_dot_prism__pb2.CreateProjectRequest.SerializeToString,
            google_dot_protobuf_dot_empty__pb2.Empty.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetProject(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/blueapi.prism.v1.Prism/GetProject',
            prism_dot_v1_dot_prism__pb2.GetProjectRequest.SerializeToString,
            prism_dot_v1_dot_prism__pb2.GetProjectResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DeleteProject(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/blueapi.prism.v1.Prism/DeleteProject',
            prism_dot_v1_dot_prism__pb2.DeleteProjectRequest.SerializeToString,
            google_dot_protobuf_dot_empty__pb2.Empty.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListProjects(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/blueapi.prism.v1.Prism/ListProjects',
            prism_dot_v1_dot_prism__pb2.ListProjectsRequest.SerializeToString,
            prism_dot_v1_dot_prism__pb2.Project.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CreateOrganization(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/blueapi.prism.v1.Prism/CreateOrganization',
            prism_dot_v1_dot_prism__pb2.CreateOrganizationRequest.SerializeToString,
            google_dot_protobuf_dot_empty__pb2.Empty.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetOrganization(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/blueapi.prism.v1.Prism/GetOrganization',
            prism_dot_v1_dot_prism__pb2.GetOrganizationRequest.SerializeToString,
            prism_dot_v1_dot_prism__pb2.GetOrganizationResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UpdateOrganization(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/blueapi.prism.v1.Prism/UpdateOrganization',
            prism_dot_v1_dot_prism__pb2.UpdateOrganizationRequest.SerializeToString,
            google_dot_protobuf_dot_empty__pb2.Empty.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DeleteOrganization(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/blueapi.prism.v1.Prism/DeleteOrganization',
            prism_dot_v1_dot_prism__pb2.DeleteOrganizationRequest.SerializeToString,
            google_dot_protobuf_dot_empty__pb2.Empty.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def VerifyUser(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/blueapi.prism.v1.Prism/VerifyUser',
            prism_dot_v1_dot_prism__pb2.VerifyUserRequest.SerializeToString,
            prism_dot_v1_dot_prism__pb2.VerifyUserResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CreateTeam(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/blueapi.prism.v1.Prism/CreateTeam',
            prism_dot_v1_dot_prism__pb2.CreateTeamRequest.SerializeToString,
            google_dot_protobuf_dot_empty__pb2.Empty.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetTeam(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/blueapi.prism.v1.Prism/GetTeam',
            prism_dot_v1_dot_prism__pb2.GetTeamRequest.SerializeToString,
            prism_dot_v1_dot_prism__pb2.GetTeamResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListTeams(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/blueapi.prism.v1.Prism/ListTeams',
            prism_dot_v1_dot_prism__pb2.ListTeamsRequest.SerializeToString,
            prism_dot_v1_dot_prism__pb2.Team.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListTeamMembers(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/blueapi.prism.v1.Prism/ListTeamMembers',
            prism_dot_v1_dot_prism__pb2.ListTeamMembersRequest.SerializeToString,
            prism_dot_v1_dot_prism__pb2.Member.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListProjectToTeam(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/blueapi.prism.v1.Prism/ListProjectToTeam',
            prism_dot_v1_dot_prism__pb2.ListProjectToTeamRequest.SerializeToString,
            prism_dot_v1_dot_prism__pb2.ListProjectToTeamResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListProducts(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/blueapi.prism.v1.Prism/ListProducts',
            prism_dot_v1_dot_prism__pb2.ListProductsRequest.SerializeToString,
            prism_dot_v1_dot_prism__pb2.Product.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CreateProduct(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/blueapi.prism.v1.Prism/CreateProduct',
            prism_dot_v1_dot_prism__pb2.CreateProductRequest.SerializeToString,
            google_dot_protobuf_dot_empty__pb2.Empty.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DeleteProduct(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/blueapi.prism.v1.Prism/DeleteProduct',
            prism_dot_v1_dot_prism__pb2.DeleteProductRequest.SerializeToString,
            google_dot_protobuf_dot_empty__pb2.Empty.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def AssignProjectToTeam(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/blueapi.prism.v1.Prism/AssignProjectToTeam',
            prism_dot_v1_dot_prism__pb2.AssignProjectToTeamRequest.SerializeToString,
            prism_dot_v1_dot_prism__pb2.AssignProjectToTeamResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DeleteTeam(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/blueapi.prism.v1.Prism/DeleteTeam',
            prism_dot_v1_dot_prism__pb2.DeleteTeamRequest.SerializeToString,
            google_dot_protobuf_dot_empty__pb2.Empty.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetIntegrationStatus(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/blueapi.prism.v1.Prism/GetIntegrationStatus',
            google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            prism_dot_v1_dot_prism__pb2.GetIntegrationStatusResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListReportSchedules(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/blueapi.prism.v1.Prism/ListReportSchedules',
            prism_dot_v1_dot_prism__pb2.ListReportSchedulesRequest.SerializeToString,
            prism_dot_v1_dot_prism__pb2.ReportSchedule.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UpdateReportSchedule(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/blueapi.prism.v1.Prism/UpdateReportSchedule',
            prism_dot_v1_dot_prism__pb2.ReportSchedule.SerializeToString,
            google_dot_protobuf_dot_empty__pb2.Empty.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CreateReportSchedule(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/blueapi.prism.v1.Prism/CreateReportSchedule',
            prism_dot_v1_dot_prism__pb2.ReportSchedule.SerializeToString,
            google_dot_protobuf_dot_empty__pb2.Empty.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UpdateOrgTimezone(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/blueapi.prism.v1.Prism/UpdateOrgTimezone',
            prism_dot_v1_dot_prism__pb2.UpdateOrgTimezoneRequest.SerializeToString,
            google_dot_protobuf_dot_empty__pb2.Empty.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListIntegrationStatus(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/blueapi.prism.v1.Prism/ListIntegrationStatus',
            prism_dot_v1_dot_prism__pb2.ListIntegrationStatusRequest.SerializeToString,
            prism_dot_v1_dot_prism__pb2.IntegrationStatus.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UpdateWorkflow(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/blueapi.prism.v1.Prism/UpdateWorkflow',
            prism_dot_v1_dot_prism__pb2.UpdateWorkflowRequest.SerializeToString,
            google_dot_protobuf_dot_empty__pb2.Empty.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListWorkflows(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/blueapi.prism.v1.Prism/ListWorkflows',
            prism_dot_v1_dot_prism__pb2.ListWorkflowsRequest.SerializeToString,
            prism_dot_v1_dot_prism__pb2.Workflow.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListActivities(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/blueapi.prism.v1.Prism/ListActivities',
            prism_dot_v1_dot_prism__pb2.ListActivitiesRequest.SerializeToString,
            prism_dot_v1_dot_prism__pb2.Activity.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def JoinOrganization(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/blueapi.prism.v1.Prism/JoinOrganization',
            prism_dot_v1_dot_prism__pb2.JoinOrganizationRequest.SerializeToString,
            google_dot_protobuf_dot_empty__pb2.Empty.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GenerateOrganizationCode(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/blueapi.prism.v1.Prism/GenerateOrganizationCode',
            prism_dot_v1_dot_prism__pb2.GenerateOrganizationCodeRequest.SerializeToString,
            prism_dot_v1_dot_prism__pb2.GenerateOrganizationCodeResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ShareGDrive(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/blueapi.prism.v1.Prism/ShareGDrive',
            prism_dot_v1_dot_prism__pb2.ShareGDriveRequest.SerializeToString,
            google_dot_protobuf_dot_empty__pb2.Empty.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
