# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: api/accountgroup.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from alphausblue.api import keyvalue_pb2 as api_dot_keyvalue__pb2
from alphausblue.api import account_pb2 as api_dot_account__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='api/accountgroup.proto',
  package='blueapi.api',
  syntax='proto3',
  serialized_options=b'\n\031cloud.alphaus.blueapi.apiB\024ApiAccountGroupProtoZ&github.com/alphauslabs/blue-sdk-go/api',
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x16\x61pi/accountgroup.proto\x12\x0b\x62lueapi.api\x1a\x12\x61pi/keyvalue.proto\x1a\x11\x61pi/account.proto\"y\n\x0c\x41\x63\x63ountGroup\x12\n\n\x02id\x18\x01 \x01(\t\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\'\n\x08metadata\x18\x03 \x03(\x0b\x32\x15.blueapi.api.KeyValue\x12&\n\x08\x61\x63\x63ounts\x18\x04 \x03(\x0b\x32\x14.blueapi.api.AccountBY\n\x19\x63loud.alphaus.blueapi.apiB\x14\x41piAccountGroupProtoZ&github.com/alphauslabs/blue-sdk-go/apib\x06proto3'
  ,
  dependencies=[api_dot_keyvalue__pb2.DESCRIPTOR,api_dot_account__pb2.DESCRIPTOR,])




_ACCOUNTGROUP = _descriptor.Descriptor(
  name='AccountGroup',
  full_name='blueapi.api.AccountGroup',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='blueapi.api.AccountGroup.id', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='name', full_name='blueapi.api.AccountGroup.name', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='metadata', full_name='blueapi.api.AccountGroup.metadata', index=2,
      number=3, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='accounts', full_name='blueapi.api.AccountGroup.accounts', index=3,
      number=4, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=78,
  serialized_end=199,
)

_ACCOUNTGROUP.fields_by_name['metadata'].message_type = api_dot_keyvalue__pb2._KEYVALUE
_ACCOUNTGROUP.fields_by_name['accounts'].message_type = api_dot_account__pb2._ACCOUNT
DESCRIPTOR.message_types_by_name['AccountGroup'] = _ACCOUNTGROUP
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

AccountGroup = _reflection.GeneratedProtocolMessageType('AccountGroup', (_message.Message,), {
  'DESCRIPTOR' : _ACCOUNTGROUP,
  '__module__' : 'api.accountgroup_pb2'
  # @@protoc_insertion_point(class_scope:blueapi.api.AccountGroup)
  })
_sym_db.RegisterMessage(AccountGroup)


DESCRIPTOR._options = None
# @@protoc_insertion_point(module_scope)
