# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: api/ripple/customfield.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1c\x61pi/ripple/customfield.proto\x12\x12\x62lueapi.api.ripple\";\n\x0b\x43ustomField\x12\n\n\x02id\x18\x01 \x01(\t\x12\x0b\n\x03key\x18\x02 \x01(\t\x12\x13\n\x0b\x64\x65scription\x18\x03 \x01(\tBl\n cloud.alphaus.blueapi.api.rippleB\x19\x41piRippleCustomFieldProtoZ-github.com/alphauslabs/blue-sdk-go/api/rippleb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'api.ripple.customfield_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\n cloud.alphaus.blueapi.api.rippleB\031ApiRippleCustomFieldProtoZ-github.com/alphauslabs/blue-sdk-go/api/ripple'
  _globals['_CUSTOMFIELD']._serialized_start=52
  _globals['_CUSTOMFIELD']._serialized_end=111
# @@protoc_insertion_point(module_scope)
