# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: api/ripple/yearmonth.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from alphausblue.api import keyvalue_pb2 as api_dot_keyvalue__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1a\x61pi/ripple/yearmonth.proto\x12\x12\x62lueapi.api.ripple\x1a\x12\x61pi/keyvalue.proto\"5\n\tYearMonth\x12(\n\tyearMonth\x18\x01 \x03(\x0b\x32\x15.blueapi.api.KeyValueBj\n cloud.alphaus.blueapi.api.rippleB\x17\x41piRippleYearMonthProtoZ-github.com/alphauslabs/blue-sdk-go/api/rippleb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'api.ripple.yearmonth_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\n cloud.alphaus.blueapi.api.rippleB\027ApiRippleYearMonthProtoZ-github.com/alphauslabs/blue-sdk-go/api/ripple'
  _YEARMONTH._serialized_start=70
  _YEARMONTH._serialized_end=123
# @@protoc_insertion_point(module_scope)
