# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: api/cover/recommendation/azurecsp.proto
# Protobuf Python Version: 6.30.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    30,
    0,
    '',
    'api/cover/recommendation/azurecsp.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\'api/cover/recommendation/azurecsp.proto\x12)blueapi.api.cover.recommendation.azurecsp\"\x19\n\x17\x41zureCSPRecommendationsB\x92\x01\n.cloud.alphaus.blueapi.api.cover.recommendationB#ApiCoverAzureCspRecommendationProtoZ;github.com/alphauslabs/blue-sdk-go/api/cover/recommendationb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'api.cover.recommendation.azurecsp_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n.cloud.alphaus.blueapi.api.cover.recommendationB#ApiCoverAzureCspRecommendationProtoZ;github.com/alphauslabs/blue-sdk-go/api/cover/recommendation'
  _globals['_AZURECSPRECOMMENDATIONS']._serialized_start=86
  _globals['_AZURECSPRECOMMENDATIONS']._serialized_end=111
# @@protoc_insertion_point(module_scope)
