# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: api/cover/recommendation/octoaws.proto
# Protobuf Python Version: 5.27.2
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    27,
    2,
    '',
    'api/cover/recommendation/octoaws.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n&api/cover/recommendation/octoaws.proto\x12(blueapi.api.cover.recommendation.octoaws\"\x14\n\x12\x41WSRecommendationsB\xa7\x01\n9cloud.alphaus.blueapi.api.cover.recommendation.octoawsrecB\"ApiCoverOctoAwsRecommendationProtoZFgithub.com/alphauslabs/blue-sdk-go/api/cover/recommendation/octoawsrecb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'api.cover.recommendation.octoaws_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n9cloud.alphaus.blueapi.api.cover.recommendation.octoawsrecB\"ApiCoverOctoAwsRecommendationProtoZFgithub.com/alphauslabs/blue-sdk-go/api/cover/recommendation/octoawsrec'
  _globals['_AWSRECOMMENDATIONS']._serialized_start=84
  _globals['_AWSRECOMMENDATIONS']._serialized_end=104
# @@protoc_insertion_point(module_scope)
